### ISSUE TITLE
Internal Error: Bindings not found. - New Error since recently 

### ISSUE THREAD

**Issue by essuraj** [fabien0102/openapi-codegen#239]
openapi-codegen gen catalog

Internal Error: Bindings not found.
    at Compiler.<anonymous> (/***********/******/node_modules/@swc/core/index.js:259:23)
    at Generator.next (<anonymous>)
    at /***********/******/node_modules/@swc/core/index.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/***********/******/node_modules/@swc/core/index.js:30:12)
    at Compiler.transformFile (/***********/******/node_modules/@swc/core/index.js:254:16)
    at Module.transformFile (/***********/******/node_modules/@swc/core/index.js:352:21)
    at GenerateCommand.loadConfigs (file:///***********/******/node_modules/@openapi-codegen/cli/lib/cli.js:77451:40)
    at GenerateCommand.execute (file:///***********/******/node_modules/@openapi-codegen/cli/lib/cli.js:77552:36)
    at GenerateCommand.validateAndExecute (/***********/******/node_modules/clipanion/lib/advanced/Command.js:73:37)

 *  The terminal process "/opt/homebrew/bin/zsh '-l', '-c', 'npm run build:catalog-api'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by essuraj** [comment]
No Change in any code, no updated to plugin

**Comment by essuraj** [comment]
Cleared up after removing package-lock and node_modules and doing` npm i `again
